# See http://docs.travis-ci.com/user/languages/csharp/ for details

language: csharp
sudo: required
dist: trusty
dotnet: 2.1.4
git:
  depth: 9999999

script:
  - ./build.sh --target Travis -- -runCoverage=false -framework="netstandard1.3" -testFramework="netcoreapp2.0"